//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticProgress.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProgressLogisticEntities : DbContext
    {
        private static ProgressLogisticEntities _context = new ProgressLogisticEntities();
        public ProgressLogisticEntities()
            : base("name=ProgressLogisticEntities")
        {
        }
    
        public static ProgressLogisticEntities GetContext()
        {
            if(_context == null)
            {
                _context = new ProgressLogisticEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<DeliveryRequest> DeliveryRequests { get; set; }
        public virtual DbSet<DevReq_Prod> DevReq_Prod { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<PurchaceInvoce> PurchaceInvoces { get; set; }
        public virtual DbSet<PurInv_Prod> PurInv_Prod { get; set; }
        public virtual DbSet<Selling> Sellings { get; set; }
        public virtual DbSet<Selling_Prod> Selling_Prod { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
