//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticProgress.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryRequest()
        {
            this.DevReq_Prod = new HashSet<DevReq_Prod>();
        }
    
        public int DevReqId { get; set; }
        public int ReqNum { get; set; }
        public System.DateTime DateOfPreparation { get; set; }
        public System.DateTime DateOfDelivery { get; set; }
        public int ComplierId { get; set; }
        public int SupplierId { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevReq_Prod> DevReq_Prod { get; set; }
    }
}
