//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticProgress.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurInv_Prod
    {
        public int PurInvId { get; set; }
        public int ProdId { get; set; }
        public int Qty { get; set; }
        public int Price { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual PurchaceInvoce PurchaceInvoce { get; set; }
    }
}
